<?
$PERM["bitrix"]["14"]="R";
$PERM["externalsites"]["12"]="T_8";
$PERM["externalsites"]["16"]="T_10";
$PERM["externalsites"]["15"]="T_8";
$PERM["externalsites"]["14"]="T_8";
$PERM["externalsites"]["*"]="D";
$PERM["upload"]["14"]="T_8";
$PERM["upload"]["*"]="R";
$PERM["upload"]["5"]="T_8";
$PERM["/"]["13"]="T_10";
$PERM["/"]["12"]="R";
$PERM["/"]["*"]="D";
$PERM["/"]["2"]="D";
$PERM["about"]["9"]="T_9";
$PERM["company"]["9"]="T_9";
$PERM["pub"]["*"]="R";
$PERM["pub"]["5"]="T_8";
$PERM["online"]["*"]="R";
$PERM["desktop_app"]["*"]="R";
?>